<a href="https://colab.research.google.com/github/Gduro/Data-Science/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
dir()

['In',
 'Out',
 '_',
 '_1',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'exit',
 'get_ipython',
 'np',
 'quit']

In [ ]:
dir(np
)

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

In [ ]:
print(x)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype


dtype('int64')

In [ ]:
x = np.array([1.3, 2.5, 1.4])
print(x)

[1.3 2.5 1.4]


2D Array


In [ ]:
x = np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim


2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[1,2,4], [2,5,6]])
x

array([[1, 2, 4],
       [2, 5, 6]])

In [ ]:
x.shape

(2, 3)

3D array


In [ ]:
x = np.array(
    [[[3, 4, 1], 
        [3, 1,2]],
     
      [[4,1,3],
        [4,2,1]],
      [[4,1,3],
        [4,2,1]]]

)


x

array([[[3, 4, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
x.shape

(3, 2, 3)

**Typy Danych**


In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
a = np.array([1.0 , 2.4, 5.4])
a.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
a = np.array([1.0 , 2.4, 5.7], dtype='int')
a.dtype

dtype('int64')

In [ ]:
a

array([1, 2, 5])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
  np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
  np.arange(start=10, stop=100, step=10 )

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
  np.arange(start=100, stop=10, step=-10 )

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1))   

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach


In [ ]:
A = np.array([3, 1, 4, 2])
B= np.array([3,-1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B


array([6, 0, 7, 4])

In [ ]:
A % B
  

array([0, 0, 1, 0])

In [ ]:
A / B


array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3


array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A + 3* 8


array([27, 25, 28, 26])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B
            )

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
x = np.array([[1,3], [-2,8]])
y = np.array([[6,8], [-1,2]])
print(x, '\n')
print(y)  

[[ 1  3]
 [-2  8]] 

[[ 6  8]
 [-1  2]]


Mnożenie macierzy nie jest przemienne


In [ ]:
 np.dot(x, y)

array([[  3,  14],
       [-20,   0]])

In [ ]:
x* y


array([[ 6, 24],
       [ 2, 16]])

In [ ]:
x.dot(y)

array([[  3,  14],
       [-20,   0]])

In [ ]:
y.dot(x)

array([[-10,  82],
       [ -5,  13]])

In [ ]:
x @ y

array([[  3,  14],
       [-20,   0]])

Generowanie liczb pseudolosowych


In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(1)

array([1.45427351])

In [ ]:
np.random.randn(10, 4)

array([[-0.51080514, -1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117],
       [-0.67246045, -0.35955316, -0.81314628, -1.7262826 ],
       [ 0.17742614, -0.40178094, -1.63019835,  0.46278226],
       [-0.90729836,  0.0519454 ,  0.72909056,  0.12898291],
       [ 1.13940068, -1.23482582,  0.40234164, -0.68481009],
       [-0.87079715, -0.57884966, -0.31155253,  0.05616534],
       [-1.16514984,  0.90082649,  0.46566244, -1.53624369],
       [ 1.48825219,  1.89588918,  1.17877957, -0.17992484],
       [-1.07075262,  1.05445173, -0.40317695,  1.22244507]])

In [ ]:
np.random.rand()

0.8811031971111616

In [ ]:
np.random.rand(10,2)

array([[0.58127287, 0.88173536],
       [0.69253159, 0.72525428],
       [0.50132438, 0.95608363],
       [0.6439902 , 0.42385505],
       [0.60639321, 0.0191932 ],
       [0.30157482, 0.66017354],
       [0.29007761, 0.61801543],
       [0.4287687 , 0.13547406],
       [0.29828233, 0.56996491],
       [0.59087276, 0.57432525]])

In [ ]:
np.random.randint(15) #losowa wartość całkowita z przedziału 0-15

8

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([77, 92, 13, 86, 45, 96, 71, 79, 97, 53])

In [ ]:
np.random.choice([4, 2,3,1])

3

In [ ]:
np.random.choice(['python', 'java', 'sql', 'php'])

'java'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([4, 5, 0, 9, 6, 1, 7, 3, 2, 8])

In [ ]:
data

array([4, 5, 0, 9, 6, 1, 7, 3, 2, 8])

podstawowe funkcje w bibliotece numpy

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(2)

7.38905609893065

In [ ]:
np.sqrt(6)

2.449489742783178

In [ ]:
np.all([2, 3, 1, 0])

False

In [ ]:
np.any([0,0,0,])

False

In [ ]:
bool(1.5)

True

In [ ]:
a = np.random.randn(5)
a

array([-0.36408678,  1.34395442, -0.81822096,  0.08270994, -1.29105846])

In [ ]:
np.argmax(a) #pokazanie najwyższej wartości z listy

1

In [ ]:
a[np.argmax(a)]

1.343954419584932

In [ ]:
a

array([-0.36408678,  1.34395442, -0.81822096,  0.08270994, -1.29105846])

In [ ]:
np.argmin(a)

4

In [ ]:
np.argsort(a)

array([4, 2, 0, 3, 1])

In [ ]:
np.max(a)

1.343954419584932

In [ ]:
np.min(a)

-1.291058455346977

In [ ]:
np.mean(a) #liczy średnią

-0.20934036741486084

In [ ]:
np.median(a)

-0.3640867757814793

In [ ]:
np.std(a)

0.9014226672581676

indeksowanie i wycinanie tablic

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# a[index], a[start:stop], a[:stop], a[start:]

In [ ]:
a[2]

2

In [ ]:
a

In [ ]:
a[2:] # od 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
a[:2] # do 2 

array([0, 1])

In [ ]:
a[[0,2]]

array([0, 2])

In [ ]:
a[-1]

19

In [ ]:
a[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[0] #wycinamy cały 1 wiersz

array([0, 1, 2, 3, 4])

In [ ]:
a[1]

array([5, 6, 7, 8, 9])

In [ ]:
a[:, 0] #wycinanie kolumny

array([ 0,  5, 10, 15])

In [ ]:
a[1, 1]

6

In [ ]:
a[1, 3]

8

In [ ]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
a[1, 2] =14  # zmiana wartości
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

NameError: ignored

In [2]:
a


NameError: ignored

In [5]:
A

NameError: ignored

In [10]:
a = np.arange(20)

In [11]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
a.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
a.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Maski Logiczne


In [20]:
A = np.arange(start=-10, stop=10, step=0.5)
A= A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [22]:
A > 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [24]:
np.bitwise_and(A > -5, A< 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
A[np.bitwise_and(A > -5, A< 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [26]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])